server {
    listen 80;
    listen [::]:80;
    server_name shellr.net www.shellr.net dma.shellr.net grafana.shellr.net status.shellr.net;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
