server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name status.shellr.net;

    include /etc/nginx/snippets/tls_common.conf;
    include /etc/nginx/snippets/security_headers.conf;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        include /etc/nginx/snippets/proxy_common.conf;
        proxy_pass http://genesis-monitoring-uptime-kuma:3001;
    }
}
