ssl_certificate /etc/letsencrypt/live/shellr.net/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/shellr.net/privkey.pem;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:10m;
ssl_session_tickets off;
ssl_prefer_server_ciphers off;
